name = "proof"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Proof"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.0"

[[require]]
name = "duper"
scope = "leanprover-community"
rev = "v4.25.0"

[[require]]
name = "Canonical"
scope = "chasenorman"
rev = "v4.25.0"

[[lean_lib]]
name = "Proof"
